import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <div className='header w-full max-w-[1200px] mx-auto px-4'>
            <div>
              <p className='text-lg text-white-100'>
                A showcase of my work and projects :3
              </p>
            </div>

            <div className='flex gap-6'>
              <Link href='/' className='text-sm font-bold'>
                Home
              </Link>
              <Link href='/projects' className='text-sm font-bold'>
                Projects
              </Link>
              <Link href='/competitions' className='text-sm font-bold'>
                Competitions
              </Link>
              <Link href='/about' className='text-sm font-bold'>
                About Me
              </Link>
            </div>
          </div>

          {children}
        </div>
      </body>
    </html>
  );
}
